Feature paj 8 doctor user creation
infoshareacademy/jpydzr3-pajtonersi pull request #13
Opened 2021-10-28 19:40 UTC by ewelina-jeschke

stworzyłam nowy plik add_user.py, ponieważ funkcja add_user w klasie admin zapętlała się (miałam import doktora w adminie i import admina w doktorze). Ta funkcja potem jest do przeniesienia na user_repository albo do innego pliku

2021-10-29 20:41 UTC, jaroslaw-majka requested changes
Czołem,
wygląda jakbyś nie usuneła linijek, które służyły Ci do testów?

2021-10-29 20:41 UTC, jaroslaw-majka commented on users/user_classes/add_user.py
> +        # )
Po co te zakomentowane linijki?

2021-10-29 20:41 UTC, jaroslaw-majka commented on users/user_classes/add_user.py
> +        # )
Po co te zakomentowane linijki?

2021-10-29 20:41 UTC, jaroslaw-majka commented on users/user_classes/add_user.py
> +        # )
Po co te zakomentowane linijki?

2021-10-29 20:41 UTC, jaroslaw-majka commented on users/user_classes/add_user.py
> +add_user('cos')
To wywołanie było do testów? 
Jak tak to do wyrzucenia :)

2021-10-29 20:41 UTC, jaroslaw-majka commented on users/user_classes/add_user.py
> +        print(vars(patient))
Zamiast print wolałbym return patient

2021-10-29 20:41 UTC, jaroslaw-majka commented on users/user_classes/add_user.py
> +        print(vars(receptionist))
Zamiast print wolałbym return receptionist

2021-10-29 20:41 UTC, jaroslaw-majka commented on users/user_classes/add_user.py
> +    receptionist_creation()
To było do testów? Jak tak to do usunięcia

2021-10-29 20:41 UTC, jaroslaw-majka commented on users/user_classes/add_user.py
> +        print(vars(doctor))
Zamiast print wolę return doctor

2021-10-29 20:41 UTC, jaroslaw-majka commented on users/user_classes/add_user.py
> +    doctor_creation()
Jak to było do testów to do usunięcia

2021-11-13 10:32 UTC, KMdev94 approved these changes

2021-11-13 10:33 UTC, merged