Dev reformatting
infoshareacademy/jpydzr3-pajtonersi pull request #6
Opened 2021-10-14 20:23 UTC by ewelina-jeschke

Pls verify: admin_user, master_user, class_patient, class_doctor, class_receptionist

2021-10-15 11:11 UTC, jaroslaw-majka requested changes
Dobra robota! 
Wrzuciłem kilka komentarzy :)

2021-10-15 11:11 UTC, jaroslaw-majka commented on admin_menu.py
> +
"Literówka"?

2021-10-15 11:11 UTC, jaroslaw-majka commented on master_user.py
>          self.password = None
Wiem, że to ja sam tworzyłem te 2 atrybuty, ale możesz chcesz spróbować zrobić dla nich setter i getter?
W artykule podesłanym przez Karola jest to fajnie rozpisane: https://www.programiz.com/python-programming/property

2021-10-15 11:11 UTC, jaroslaw-majka commented on master_user.py
> +        self.account_status = account_status
Widze, że zmieniłaś kolejność tych atrybutów. W funkcjonowaniu programu nie będzie to nic zaburzało, ale dobrą praktyką podobno jest, aby kolejność tutaj zgadzała się z tą w nawiasie przy definiowaniu metody.

2021-10-15 17:24 UTC, ewelina-jeschke commented on admin_menu.py
> +
corrected

2021-10-15 19:17 UTC, ewelina-jeschke commented on master_user.py
>          self.password = None
ok, zajme się tym

2021-10-17 09:38 UTC, jaroslaw-majka requested changes

2021-10-17 09:38 UTC, jaroslaw-majka commented on master_user.py
> +
Za dużo pustych linijek :)

2021-10-17 11:46 UTC, merged